In [17]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [18]:
from google.colab import files
uploaded = files.upload()

Saving data.xlsx to data (2).xlsx

In [19]:
df = pd.read_excel('data.xlsx')
df.head()

                           test  class
0             I love Bangladesh      1
1  Could you give me an iphone?      0
2            Hello how are you?      1
3           I want to talk you.      1

In [20]:
df.shape

(4, 2)

# ***Count Vectorizer***

In [21]:
cv = CountVectorizer()

In [22]:
x = cv.fit_transform(df['test'])
x

<4x14 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [23]:
x.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]])

In [24]:
df2 = df.copy()

In [25]:
df3 = pd.DataFrame(x.toarray(), index=df['test'], columns=cv.get_feature_names_out())

In [26]:
df3.head()

,an,are,bangladesh,could,give,hello,how,iphone,love,me,talk,to,want,you
test,,,,,,,,,,,,,,
I love Bangladesh,0,0,1,0,0,0,0,0,1,0,0,0,0,0
Could you give me an iphone?,1,0,0,1,1,0,0,1,0,1,0,0,0,1
Hello how are you?,0,1,0,0,0,1,1,0,0,0,0,0,0,1
I want to talk you.,0,0,0,0,0,0,0,0,0,0,1,1,1,1

In [27]:
columns=cv.get_feature_names_out()
columns

array(['an', 'are', 'bangladesh', 'could', 'give', 'hello', 'how',
       'iphone', 'love', 'me', 'talk', 'to', 'want', 'you'], dtype=object)

# ***TF-IDF vectorizer***

In [28]:
idf = TfidfVectorizer()

In [29]:
x = idf.fit_transform(df2['test'])

In [30]:
x.toarray()

array([[0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.43003652, 0.        , 0.        , 0.43003652, 0.43003652,
        0.        , 0.        , 0.43003652, 0.        , 0.43003652,
        0.        , 0.        , 0.        , 0.27448674],
       [0.        , 0.5417361 , 0.        , 0.        , 0.        ,
        0.5417361 , 0.5417361 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.34578314],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.5417361 , 0.5417361 , 0.5417361 , 0.34578314]])

In [31]:
df4 = pd.DataFrame(x.toarray(),index=df['test'],columns=idf.get_feature_names_out())

In [32]:
df4.head()

,an,are,bangladesh,could,give,hello,how,iphone,love,me,talk,to,want,you
test,,,,,,,,,,,,,,
I love Bangladesh,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000
Could you give me an iphone?,0.430037,0.000000,0.000000,0.430037,0.430037,0.000000,0.000000,0.430037,0.000000,0.430037,0.000000,0.000000,0.000000,0.274487
Hello how are you?,0.000000,0.541736,0.000000,0.000000,0.000000,0.541736,0.541736,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.345783
I want to talk you.,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.541736,0.541736,0.541736,0.345783

# ***Word2Vec***

In [33]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.0.post1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)

In [34]:
import gensim
from gensim.models import Word2Vec

In [35]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [37]:
text_vsc = [word_tokenize(test) for test in df['test']]
print(text_vsc)

[['I', 'love', 'Bangladesh'], ['Could', 'you', 'give', 'me', 'an', 'iphone', '?'], ['Hello', 'how', 'are', 'you', '?'], ['I', 'want', 'to', 'talk', 'you', '.']]

In [39]:
text = []
for test in df['test']:
    text.append(nltk.word_tokenize(test))
text

[['I', 'love', 'Bangladesh'],
 ['Could', 'you', 'give', 'me', 'an', 'iphone', '?'],
 ['Hello', 'how', 'are', 'you', '?'],
 ['I', 'want', 'to', 'talk', 'you', '.']]

In [43]:
model = Word2Vec(text,min_count=1) #min_count=1 => eikhane 1 bar .same type value kobar hole hount korbe,by default its 5

In [42]:
model

In [41]:
model.wv.most_similar('Bangladesh')

[('Hello', 0.16695067286491394),
 ('love', 0.13887985050678253),
 ('an', 0.13149002194404602),
 ('?', 0.06408979743719101),
 ('me', 0.06059184670448303),
 ('iphone', 0.04767157509922981),
 ('are', 0.044106729328632355),
 ('talk', 0.019987381994724274),
 ('Could', 0.019152285531163216),
 ('I', 0.009391160681843758)]